"""reinitialize models

Revision ID: d43ba2c3c0f0
Revises: c7cfcda4ce4a
Create Date: 2023-02-17 14:36:55.389922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd43ba2c3c0f0'
down_revision = 'c7cfcda4ce4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=80), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
